# This is the configuration file for Iac Scan APIv2.

# Specify the template types.The valid values are TF, CFT, K8S
template_type: CFT

# For your template_type, fill in the details where applicable.
# variables: Specify any environment variables(TF) or parameters(CFT) as key:value pairs under this attribute.
# variable_files: Specify all the custom variable_files under here. It is an array of strings.
# variable_files: If it is standard extension(.tfvars for terraform), then this can be omitted.
# variable_files: For a custom extension, specify the variable file path from the root of the repo.
template_parameters:
  variable_files:
  - './variables.yml'
